### ISSUE TITLE
update Comm to Mkt / EMu MM

### ISSUE THREAD

**Issue by magpiedin** [fieldmuseum/dams-netx#50]
Update SecDepartment_tab from Communications to Marketing for Multimedia in EMu

(KW - followup by removing 'Communications' folder from NetX

**Comment by rondlg** [comment]
@magpiedin 

Communications Security Department is now replaced by Marketing in: 
- emultimedia
- enarratives
- eevents
- eparties

and I have removed it from the lookup list. If it pops up anywhere else let me know. If it crops up elsewhere let me know

EMu documentation cross reference issue: https://github.com/fieldmuseum/EMu-Documentation/issues/1223
