### ISSUE TITLE
Page - Field Content Plan - 2021 Q1-Q2 toolkits

### ISSUE THREAD

**Issue by magpiedin** [fieldmuseum/dams-netx#53]
un-used section? -- e.g.:

https://brandcenter.fieldmuseum.org/content/index/guid/january_2021

1. Is this section still needed?
2. If so, is it better to shift to field-main/Dato, or to NetX?  (Either way, would need to setup editor-permissions &/or content-update workflows.)

**Comment by rondlg** [comment]
I'd make a pdf and file it away!

**Comment by rondlg** [comment]
Feels like this [googlesheet](https://docs.google.com/spreadsheets/d/1S5YpjO4QtPkwB3w6NVI2iGcARMemAA049o9_PMnJldw) is still active, but it is the only thing I can see.

**Comment by mphx2** [comment]
It looks like that section on the brand center has links to toolkits & such (DropBox mostly, but some to the [Exhibition Resources](https://sites.google.com/a/fieldmuseum.org/workingteamtest/exhibition-schedule)). There is a link to the main DropBox folder on that FCP spreadsheet, and since there older, I don't think we need them?

**Comment by rondlg** [comment]
The toolkits themselves move out of dropbox and into dato/be archived in EMu maybe?

**Comment by magpiedin** [comment]
Thanks all -- The brandcenter cites pages listed under "2021 Q1-Q2 toolkits" in the nav menu are now logged in this issue and won't be moved to the NetX portal.

They point[ed] to these dropbox & a few other links below:
(And I think these & similar dropbox assets should be archived in EMu if still available. I'll follow up with Bridgette/Bea &/or Exh folks about where to start with that)

### January 2021 ([_screencap pdf_](https://github.com/user-attachments/files/17820363/screencapture-brandcenter-fieldmuseum-org-content-index-guid-january-2021-2024-11-19-13_18_25.pdf)):
- **Dropbox:** [Around the World Destinations](https://www.dropbox.com/home/Field%20Content%20Plan%20(1)/2021/01.2021/Around%20the%20World%20Destinations): Cyrus Tang Hall of China, Ancient Egypt, Ancient Americas, Restoring Earth
- **Exh. Resources site:** [Apsáalooke Women and Warriors](https://sites.google.com/a/fieldmuseum.org/workingteamtest/currentexhibitions/aps%C3%A1alooke-women-and-warriors?authuser=0)

### February 2021 ([_screencap pdf_](https://github.com/user-attachments/files/17820362/screencapture-brandcenter-fieldmuseum-org-content-index-guid-february-2021-2024-11-19-13_18_46.pdf)):
- **Dropbox:** [Around the World Destinations](https://www.dropbox.com/home/Field%20Content%20Plan%20(1)/2021/02.2021/Around%20the%20World%20Destinations): Cyrus Tang Hall of China, Ancient Egypt, Ancient Americas, Restoring Earth
- **Dropbox:**
[Black History Month](https://www.dropbox.com/home/Field%20Content%20Plan%20(1)/2021/02.2021/Black%20History%20Month)


### March 2021 ([_screencap pdf_](https://github.com/user-attachments/files/17820361/screencapture-brandcenter-fieldmuseum-org-content-index-guid-march-2021-2024-11-19-13_19_07.pdf)):
- **Exh. Resources site:** [Apsáalooke Women and Warriors](https://sites.google.com/a/fieldmuseum.org/workingteamtest/currentexhibitions/aps%C3%A1alooke-women-and-warriors?authuser=0)
- **Dropbox:** [Hall 8 process/ behind-the-scenes](https://www.dropbox.com/home/Field%20Content%20Plan%20(1)/2021/03.2021/Hall%208%20BTS)
- **Dropbox:** [Women's History Month](https://www.dropbox.com/home/Field%20Content%20Plan%20(1)/2021/03.2021/Women's%20History%20Month)


### April 2021 ([_screencap pdf_](https://github.com/user-attachments/files/17820360/screencapture-brandcenter-fieldmuseum-org-content-index-guid-april-2021-1-2024-11-19-13_19_21.pdf)):
- **Dropbox:** [Hero](https://www.dropbox.com/home/Field%20Content%20Plan%20(1)/2021/04.2021)


### May 2021  ([_screencap pdf_](https://github.com/user-attachments/files/17820359/screencapture-brandcenter-fieldmuseum-org-content-index-guid-may-2021-2024-11-19-13_19_30.pdf)):
- **Exh. Resources site:** [Becoming Jane](https://sites.google.com/a/fieldmuseum.org/workingteamtest/upcomingexhibitions/becoming-jane)
- **Dropbox:** [Virtual WIS Luncheon (5/6)](https://www.dropbox.com/home/Field%20Content%20Plan%20(1)/2021/05.2021)


### June 2021 ([_screencap pdf_](https://github.com/user-attachments/files/17820357/screencapture-brandcenter-fieldmuseum-org-content-index-guid-june-2021-2024-11-19-13_19_43.pdf)):
- **Exh. Resources site:** [Becoming Jane](https://sites.google.com/a/fieldmuseum.org/workingteamtest/upcomingexhibitions/becoming-jane)
